name: Update lastUpdated

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Update lastUpdated
      run: |
        gem install octokit
        rake lastUpdated
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: push
    - name: push
      run: |
        git config --global user.name 'Sketch Developer'
        git config --global user.email 'developer@sketch.com'
        git add plugins.json
        git commit -am 'Update lastUpdated'
        git push
